"""add prix_free produits admin_note to colis

Revision ID: 7d5df18aff59
Revises:
Create Date: 2026-03-15 20:38:53.732031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5df18aff59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colis', sa.Column('prix_free', sa.Float(), nullable=True))
    op.add_column('colis', sa.Column('produits', sa.JSON(), nullable=True))
    op.add_column('colis', sa.Column('admin_note', sa.String(), nullable=True))
    op.drop_index(op.f('ix_colis_numero_suivi'), table_name='colis')
    op.create_unique_constraint(None, 'colis', ['numero_suivi'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'colis', type_='unique')
    op.create_index(op.f('ix_colis_numero_suivi'), 'colis', ['numero_suivi'], unique=True)
    op.drop_column('colis', 'admin_note')
    op.drop_column('colis', 'produits')
    op.drop_column('colis', 'prix_free')
    # ### end Alembic commands ###
